"""Add row and column to seats table

Revision ID: 737258ce25cb
Revises: 001
Create Date: 2026-05-01 11:22:58.673111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = '737258ce25cb'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.00'))
    # Add columns as nullable first to handle existing data
    op.add_column('seats', sa.Column('row', sa.Integer(), nullable=True))
    op.add_column('seats', sa.Column('column', sa.Integer(), nullable=True))
    op.add_column('seats', sa.Column('is_sleeper', sa.Boolean(), nullable=True))
    # Convert deck from enum to integer - add temp column, migrate, drop old, rename
    op.add_column('seats', sa.Column('deck_int', sa.Integer(), nullable=True))
    op.execute(text("""
        UPDATE seats 
        SET deck_int = CASE 
            WHEN deck = 'LOWER' THEN 0 
            WHEN deck = 'UPPER' THEN 1 
            ELSE 0 
        END
    """))
    op.drop_column('seats', 'deck')
    op.alter_column('seats', 'deck_int', new_column_name='deck', nullable=True)
    op.drop_column('seats', 'seat_type')
    
    # Populate existing seats with default row/column values based on seat_number
    op.execute(text("""
        UPDATE seats 
        SET "row" = ((CAST(REPLACE(seat_number, 'S', '') AS INTEGER) - 1) / 4) + 1,
            "column" = ((CAST(REPLACE(seat_number, 'S', '') AS INTEGER) - 1) % 4) + 1
        WHERE "row" IS NULL
    """))
    
    # Now make columns non-nullable
    op.alter_column('seats', 'row', nullable=False)
    op.alter_column('seats', 'column', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('seat_type', postgresql.ENUM('SLEEPER', 'SEATER', name='seattype'), autoincrement=False, nullable=False))
    op.alter_column('seats', 'deck',
               existing_type=sa.Integer(),
               type_=postgresql.ENUM('LOWER', 'UPPER', name='deck'),
               nullable=False)
    op.drop_column('seats', 'is_sleeper')
    op.drop_column('seats', 'column')
    op.drop_column('seats', 'row')
    op.drop_column('bookings', 'total_price')
    # ### end Alembic commands ###
